/*
Copyright 2026 Poda contributors

SPDX-License-Identifier: AGPL-3.0-only OR GPL-3.0-only OR LicenseRef-Element-Commercial
Please see LICENSE files in the repository root for full details.
*/

import { type CustomTheme } from "./theme";

export const PODA_LIGHT_THEME_NAME = "Poda Light";
export const PODA_DARK_THEME_NAME = "Poda Dark";
export const PODA_LIGHT_THEME_ID = `custom-${PODA_LIGHT_THEME_NAME}`;
export const PODA_DARK_THEME_ID = `custom-${PODA_DARK_THEME_NAME}`;

const accentScale = {
    "accent-color-100": "#fff8e8",
    "accent-color-200": "#ffebc7",
    "accent-color-300": "#fad990",
    "accent-color-400": "#f9c66b",
    "accent-color-500": "#f9ba51",
    "accent-color-600": "#efa43e",
    "accent-color-700": "#e5793e",
    "accent-color-800": "#c25821",
    "accent-color-900": "#9b461b",
    "accent-color-1000": "#743719",
    "accent-color-1100": "#563522",
    "accent-color-1200": "#452a1b",
    "accent-color-1300": "#332216",
    "accent-color-1400": "#241710",
};

const commonCompound = {
    "--cpd-color-bg-action-primary-rest": "#f9ba51",
    "--cpd-color-bg-action-primary-hovered": "#efa43e",
    "--cpd-color-bg-action-primary-pressed": "#e5793e",
    "--cpd-color-bg-action-primary-disabled": "#f4d7a8",
    "--cpd-color-text-on-solid-primary": "#332216",
    "--cpd-color-icon-on-solid-primary": "#332216",
    "--cpd-color-text-action-primary": "#332216",
};

export const PODA_LIGHT_THEME: CustomTheme = {
    name: PODA_LIGHT_THEME_NAME,
    is_dark: false,
    fonts: {
        faces: [],
        general: 'Inter, "Apple Color Emoji", "Segoe UI Emoji", Arial, sans-serif',
        monospace: '"Fira Code", "Courier New", monospace',
    },
    colors: {
        ...accentScale,
        "accent-color": "#006052",
        "primary-color": "#f9ba51",
        "warning-color": "#b3261e",
        "sidebar-color": "#332216",
        "roomlist-background-color": "#fff8e8",
        "roomlist-text-color": "#332216",
        "roomlist-text-secondary-color": "#6b5142",
        "roomlist-highlights-color": "#ffebc7",
        "roomlist-separator-color": "#e6d5c7",
        "timeline-background-color": "#fffdf9",
        "timeline-text-color": "#332216",
        "timeline-text-secondary-color": "#6b5142",
        "timeline-highlights-color": "#fff1d8",
        "focus-bg-color": "#fad990",
        "room-highlight-color": "#ffebc7",
        "eventbubble-self-bg": "#ffebc7",
        "eventbubble-others-bg": "#f7f1eb",
        "eventbubble-bg-hover": "#fff1d8",
        "reaction-row-button-selected-bg-color": "#fad990",
        "menu-selected-color": "#fff1d8",
        "other-user-pill-bg-color": "#ffebc7",
        "strong-input-border-color": "#9b461b",
        "icon-button-color": "#6b5142",
        "links": "#006052",
        "primary-content": "#332216",
        "secondary-content": "#6b5142",
        "tertiary-content": "#765e4f",
        "quaternary-content": "#8e7463",
        "quinary-content": "#a58e7f",
        "system": "#fff8e8",
        "system-transparent": "#fff8e800",
        "background": "#fffdf9",
        "panels": "#fff1d8",
        "panels-actions": "#fffdf9",
    },
    compound: {
        ...commonCompound,
        "--cpd-color-bg-canvas-default": "#fffdf9",
        "--cpd-color-bg-canvas-disabled": "#f4eee7",
        "--cpd-color-bg-subtle-primary": "#fff8e8",
        "--cpd-color-bg-subtle-secondary": "#fff1d8",
        "--cpd-color-bg-action-secondary-rest": "#fffdf9",
        "--cpd-color-bg-action-secondary-hovered": "#ffebc7",
        "--cpd-color-bg-action-tertiary-hovered": "#fff1d8",
        "--cpd-color-bg-action-tertiary-selected": "#ffebc7",
        "--cpd-color-bg-accent-rest": "#fff1d8",
        "--cpd-color-text-primary": "#332216",
        "--cpd-color-text-secondary": "#6b5142",
        "--cpd-color-text-disabled": "#a58e7f",
        "--cpd-color-text-action-accent": "#743719",
        "--cpd-color-text-link-external": "#006052",
        "--cpd-color-icon-primary": "#332216",
        "--cpd-color-icon-secondary": "#6b5142",
        "--cpd-color-icon-tertiary": "#765e4f",
        "--cpd-color-icon-quaternary": "#8e7463",
        "--cpd-color-icon-disabled": "#a58e7f",
        "--cpd-color-icon-accent-primary": "#9b461b",
        "--cpd-color-icon-accent-tertiary": "#c25821",
        "--cpd-color-border-interactive-primary": "#9b461b",
        "--cpd-color-border-interactive-secondary": "#c9b5a6",
        "--cpd-color-border-interactive-hovered": "#743719",
        "--cpd-color-border-focused": "#9b461b",
        "--cpd-color-border-accent-primary": "#c25821",
        "--cpd-color-border-subtle": "#e6d5c7",
        "--cpd-color-border-disabled": "#e6d5c7",
        "--cpd-color-separator-primary": "#e6d5c7",
    },
};

export const PODA_DARK_THEME: CustomTheme = {
    name: PODA_DARK_THEME_NAME,
    is_dark: true,
    fonts: {
        faces: [],
        general: 'Inter, "Apple Color Emoji", "Segoe UI Emoji", Arial, sans-serif',
        monospace: '"Fira Code", "Courier New", monospace',
    },
    colors: {
        ...accentScale,
        "accent-color": "#006052",
        "primary-color": "#f9ba51",
        "warning-color": "#ffb4ab",
        "sidebar-color": "#1a1410",
        "roomlist-background-color": "#2c2018",
        "roomlist-text-color": "#fff8e8",
        "roomlist-text-secondary-color": "#d9c2aa",
        "roomlist-highlights-color": "#3a2d20",
        "roomlist-separator-color": "#563522",
        "timeline-background-color": "#1a1410",
        "timeline-text-color": "#fff8e8",
        "timeline-text-secondary-color": "#d9c2aa",
        "timeline-highlights-color": "#2c2018",
        "focus-bg-color": "#563522",
        "room-highlight-color": "#3a2d20",
        "eventbubble-self-bg": "#563522",
        "eventbubble-others-bg": "#2c2018",
        "eventbubble-bg-hover": "#3a2d20",
        "reaction-row-button-selected-bg-color": "#563522",
        "menu-selected-color": "#3a2d20",
        "other-user-pill-bg-color": "#563522",
        "strong-input-border-color": "#f9ba51",
        "icon-button-color": "#d9c2aa",
        "links": "#58c781",
        "primary-content": "#fff8e8",
        "secondary-content": "#d9c2aa",
        "tertiary-content": "#c6aa90",
        "quaternary-content": "#aa8e77",
        "quinary-content": "#8c725f",
        "system": "#2c2018",
        "system-transparent": "#2c201800",
        "background": "#1a1410",
        "panels": "#2c2018",
        "panels-actions": "#3a2d20",
    },
    compound: {
        ...commonCompound,
        "--cpd-color-bg-canvas-default": "#1a1410",
        "--cpd-color-bg-canvas-disabled": "#241b16",
        "--cpd-color-bg-subtle-primary": "#2c2018",
        "--cpd-color-bg-subtle-secondary": "#3a2d20",
        "--cpd-color-bg-action-secondary-rest": "#2c2018",
        "--cpd-color-bg-action-secondary-hovered": "#3a2d20",
        "--cpd-color-bg-action-tertiary-hovered": "#3a2d20",
        "--cpd-color-bg-action-tertiary-selected": "#563522",
        "--cpd-color-bg-accent-rest": "#3a2d20",
        "--cpd-color-text-primary": "#fff8e8",
        "--cpd-color-text-secondary": "#d9c2aa",
        "--cpd-color-text-disabled": "#8c725f",
        "--cpd-color-text-action-accent": "#f9ba51",
        "--cpd-color-text-link-external": "#58c781",
        "--cpd-color-icon-primary": "#fff8e8",
        "--cpd-color-icon-secondary": "#d9c2aa",
        "--cpd-color-icon-tertiary": "#c6aa90",
        "--cpd-color-icon-quaternary": "#aa8e77",
        "--cpd-color-icon-disabled": "#8c725f",
        "--cpd-color-icon-accent-primary": "#f9ba51",
        "--cpd-color-icon-accent-tertiary": "#efb855",
        "--cpd-color-border-interactive-primary": "#f9ba51",
        "--cpd-color-border-interactive-secondary": "#765943",
        "--cpd-color-border-interactive-hovered": "#efb855",
        "--cpd-color-border-focused": "#f9ba51",
        "--cpd-color-border-accent-primary": "#efb855",
        "--cpd-color-border-subtle": "#563522",
        "--cpd-color-border-disabled": "#563522",
        "--cpd-color-separator-primary": "#563522",
    },
};

export const PODA_CUSTOM_THEMES: CustomTheme[] = [PODA_LIGHT_THEME, PODA_DARK_THEME];

export function isPodaThemeId(theme: unknown): theme is string {
    return theme === PODA_LIGHT_THEME_ID || theme === PODA_DARK_THEME_ID;
}
