// Complete donor podcast + episode fixtures (donor `Podcast`, `PodcastChannel`,
// `Episode`, `EpisodeItem`, `EpisodeMedia` entities, pinned inventory).
// Mock data only — hidden internals included and made visible per maintainer choice.

export const PODCAST_FIXTURE = {
    id: "pod-field-notes",
    orgId: "org-poda-labs",
    title: "Field Notes",
    tagline: "Calm systems for chaotic launches.",
    description:
        "Weekly conversations with operators and researchers about launch systems, team rituals, and practical AI workflows. Short on hype, long on specifics.",
    slug: "field-notes",
    coverArtUrl: null,
    categories: ["Technology", "Business"],
    language: "en",
    explicit: false,
    author: "Jordan Hale",
    ownerEmail: "jordan@example.com",
    socialLinks: {
        website: "https://example.com/fieldnotes",
        twitter: "https://x.com/fieldnotes",
        linkedin: "https://linkedin.com/company/fieldnotes",
        youtube: "",
        instagram: "",
        tiktok: "",
        calendly: "",
    },
    status: "published",
    isPublic: true,
    rssFeedUrl: "https://feeds.example.com/fieldnotes.xml",
    websiteUrl: "https://example.com/fieldnotes",
    idealGuest: {
        description: "Operators who shipped something hard and can talk specifics.",
        topics: ["Launch systems", "Team rituals", "AI workflows"],
        qualities: ["Specific", "Comfortable with follow-up questions", "Shares artifacts"],
    },
    guestRequirements: {
        equipment: ["Dynamic mic or better", "Wired internet"],
        preparation: "15-min pre-call + shared run-of-show doc",
        scheduling: "Tuesdays and Thursdays, US mornings",
        other: ["Video optional", "We handle post-production"],
    },
    trailerUrl: "https://cdn.example.com/fieldnotes/trailer.mp3",
    testimonials: [
        {
            id: "pt-1",
            name: "Casey Lin",
            role: "Founder, Northbeam",
            quote: "The only launch podcast I quote in board meetings.",
            order: 1,
        },
    ],
    mediaKit: [
        {
            id: "pmk-1",
            name: "Show art pack",
            url: "https://example.com/mk/fieldnotes-art.zip",
            type: "logo",
            size: 3145728,
            filename: "fieldnotes-art.zip",
            mimeType: "application/zip",
        },
    ],
    audienceStats: {
        monthlyListeners: 18400,
        totalDownloads: 512000,
        avgEpisodeDownloads: 12190,
        topCountries: ["US", "GB", "DE", "CA"],
        demographics: "Skews 28-45, technical founders and operators",
    },
    bookingUrl: "https://calendly.com/fieldnotes/guest",
    sectionVisibility: { mediaKit: "collaborators", audienceStats: "members" },
    showType: "episodic",
    customFields: [
        { name: "Recording day", value: "Tuesdays" },
        { name: "Host timezone", value: "America/Toronto" },
    ],
    channel: {
        guid: "9b3d3e20-2f57-4f6f-9f2f-fieldnotes01",
        medium: "podcast",
        persons: [
            { name: "Jordan Hale", role: "host", group: "cast", href: "https://example.com/jordan", image: null },
            { name: "Mira Chen", role: "guest", group: "cast", href: "https://example.com/mira", image: null },
        ],
        locked: { owner: "jordan@example.com", locked: true },
        license: { identifierOrText: "CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/" },
        blocks: [],
        updateFrequency: { text: "Weekly", complete: true, dtstart: "2026-01-05T00:00:00Z", rrule: "FREQ=WEEKLY" },
        funding: [
            { title: "Support the show", url: "https://example.com/support" },
            { title: "Value4Value", url: "https://example.com/v4v" },
        ],
        value: [
            {
                type: "lightning",
                method: "keysend",
                suggested: "0.00000050000",
                recipients: [
                    {
                        name: "Jordan Hale",
                        type: "node",
                        address: "03mocknodejordanhale000000000000000000000000000000",
                        split: 90,
                        fee: false,
                    },
                    {
                        name: "Poda",
                        type: "node",
                        address: "03mocknodepoda0000000000000000000000000000000000000",
                        split: 10,
                        fee: true,
                    },
                ],
                timeSplits: [],
            },
        ],
        socialInteracts: [
            {
                disabled: false,
                uri: "https://podcastindex.social/@fieldnotes",
                protocol: "activitypub",
                accountId: "@fieldnotes@podcastindex.social",
                accountUrl: "https://podcastindex.social/@fieldnotes",
                priority: 1,
            },
        ],
        txt: [{ purpose: "verify", value: "podcastindex-verification-mock-7f3a" }],
        chat: null,
        podping: { value: false },
        trailers: [
            {
                title: "Field Notes trailer",
                url: "https://cdn.example.com/fieldnotes/trailer.mp3",
                pubdate: "2026-01-05T12:00:00Z",
                lengthBytes: 1873920,
                mimeType: "audio/mpeg",
                season: null,
            },
        ],
        locations: [
            { name: "Toronto, Canada", geo: "geo:43.6532,-79.3832", osm: "P61033", country: "CA", rel: "subject" },
        ],
        liveItems: [],
        remoteItems: [],
        podroll: null,
        publisher: {
            remoteItem: {
                feedGuid: "pub-guid-0001",
                itemGuid: null,
                feedUrl: "https://feeds.example.com/poda-publisher.xml",
                medium: "publisher",
                title: "Poda Labs",
            },
        },
    },
    currentness: {
        canonicalAt: "2026-09-01T00:00:00Z",
        activityFreshnessAt: "2026-09-10T16:00:00Z",
        internalizedAt: "2026-01-05T12:00:00Z",
        externalizedAt: null,
    },
    provenance: {
        mode: "internal",
        kind: "original",
        sourceEntryId: null,
        podcastGuid: "9b3d3e20-2f57-4f6f-9f2f-fieldnotes01",
    },
    feedDiagnostics: {
        rssFeedStatus: "valid",
        canonicalValidation: {
            status: "passing",
            warnings: ["2 items missing itunes:duration metadata", "cover art is not 3000x3000"],
            errors: [],
        },
    },
    createdAt: "2026-01-05T12:00:00Z",
    updatedAt: "2026-09-10T16:00:00Z",
};

export const EPISODES_FIXTURE = [
    {
        id: "ep-systems-collapse",
        podcastId: "pod-field-notes",
        title: "Systems that do not collapse",
        description:
            "Mira Chen on launch operating systems: runbooks, checklists, and the team rhythms that keep launch week boring. What broke, what worked, and what she'd never do again.",
        slug: "systems-that-do-not-collapse",
        duration: 2745,
        episodeNumber: 42,
        seasonNumber: 3,
        status: "published",
        showNotesHtml:
            "<p>Mira Chen on launch operating systems.</p><ul><li>The two-week runbook</li><li>Why checklists beat heroics</li></ul>",
        publishedAt: "2026-09-08T11:00:00Z",
        scheduledAt: null,
        item: {
            persons: [
                { name: "Jordan Hale", role: "host", group: "cast", href: null, image: null },
                { name: "Mira Chen", role: "guest", group: "cast", href: "https://example.com/mira", image: null },
            ],
            transcripts: [
                {
                    url: "https://cdn.example.com/ep42/transcript.vtt",
                    mimeType: "text/vtt",
                    language: "en",
                    rel: "captions",
                },
            ],
            funding: [{ title: "Support the show", url: "https://example.com/support" }],
            soundbites: [{ startTime: "1024.5", duration: "42.8", title: "The checklist that saved launch week" }],
            locations: [
                { name: "Toronto, Canada", geo: "geo:43.6532,-79.3832", osm: "P61033", country: "CA", rel: "subject" },
            ],
            chapters: {
                url: "https://cdn.example.com/ep42/chapters.json",
                mimeType: "application/json+chapters",
                language: "en",
                rel: "chapters",
            },
            license: { identifierOrText: "CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/" },
        },
        media: {
            primaryEnclosure: {
                url: "https://cdn.example.com/ep42/fieldnotes-42.mp3",
                mimeType: "audio/mpeg",
                lengthBytes: 43975000,
                durationSeconds: 2745,
                title: "MP3 128kbps",
                isDefault: true,
                bitrate: "128",
                height: null,
                language: "en",
                rel: null,
                codecs: null,
                sources: [
                    { uri: "https://cdn.example.com/ep42/fieldnotes-42.mp3", contentType: "audio/mpeg" },
                    { uri: "https://mirror.example.com/ep42/fieldnotes-42.mp3", contentType: "audio/mpeg" },
                ],
            },
            alternateEnclosures: [
                {
                    url: "https://cdn.example.com/ep42/fieldnotes-42.opus",
                    mimeType: "audio/ogg; codecs=opus",
                    lengthBytes: 26380000,
                    durationSeconds: 2745,
                    title: "Opus 64kbps",
                    isDefault: false,
                    bitrate: "64",
                    height: null,
                    language: "en",
                    rel: null,
                    codecs: "opus",
                    sources: [{ uri: "https://cdn.example.com/ep42/fieldnotes-42.opus", contentType: "audio/ogg" }],
                },
            ],
        },
        currentness: {
            canonicalAt: "2026-09-08T11:00:00Z",
            activityFreshnessAt: "2026-09-12T09:30:00Z",
            internalizedAt: "2026-09-08T11:05:00Z",
            externalizedAt: null,
        },
        provenance: {
            mode: "internal",
            kind: "original",
            sourceGuid: null,
            sourceEntryId: null,
            sourceEpisodeId: null,
        },
        guests: [
            {
                guestId: "guest-mira",
                userId: "user-mira",
                name: "Mira Chen",
                email: "mira@example.com",
                role: "guest",
                displayClass: "host_verified",
                partyKind: "person",
                tagline: "Founder ops strategist and launch systems advisor",
                appearanceDescription: "Launch operating systems deep dive",
                ctaLabel: "View profile",
                ctaUrl: "/profiles/mira-chen",
                avatarUrl: null,
                profileUrl: "/profiles/mira-chen",
            },
        ],
        createdAt: "2026-09-01T09:00:00Z",
        updatedAt: "2026-09-08T12:10:00Z",
    },
    {
        id: "ep-research-loops",
        podcastId: "pod-field-notes",
        title: "Research loops with agents (working title)",
        description:
            "Draft: how teams actually use AI-assisted research before a launch, with real examples and failure modes.",
        slug: "research-loops-with-agents",
        duration: null,
        episodeNumber: 43,
        seasonNumber: 3,
        status: "scheduled",
        showNotesHtml: null,
        publishedAt: null,
        scheduledAt: "2026-09-22T11:00:00Z",
        item: {
            persons: [{ name: "Jordan Hale", role: "host", group: "cast", href: null, image: null }],
            transcripts: [],
            funding: [],
            soundbites: [],
            locations: [],
            chapters: null,
            license: { identifierOrText: "CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/" },
        },
        media: { primaryEnclosure: null, alternateEnclosures: [] },
        currentness: {
            canonicalAt: null,
            activityFreshnessAt: "2026-09-14T18:00:00Z",
            internalizedAt: null,
            externalizedAt: null,
        },
        provenance: { mode: "internal", kind: "draft", sourceGuid: null, sourceEntryId: null, sourceEpisodeId: null },
        guests: [],
        createdAt: "2026-09-12T10:00:00Z",
        updatedAt: "2026-09-14T18:00:00Z",
    },
];
